name: Check

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Code Style
    uses: ihostage/.github-play/.github/workflows/sbt.yml@sharable-actions
    with:
      cmd: sbt validateCode

  check-binary-compatibility:
    name: Binary Compatibility
    uses: ihostage/.github-play/.github/workflows/binary-check.yml@sharable-actions

  check-docs:
    name: Docs
    uses: ihostage/.github-play/.github/workflows/sbt.yml@sharable-actions
    with:
      cmd: sbt docs/validateDocs

  tests:
    name: Tests
    needs: # Waiting more lightweight checks
      - "check-code-style"
      - "check-binary-compatibility"
      - "check-docs"
    uses: ihostage/.github-play/.github/workflows/sbt-matrix.yml@sharable-actions
    with: # Should be sync with Mergify conditions (.mergify.yml)
      java: >-
        [ "11", "8" ]
      scala: >-
        [ "2.12.15", "2.13.8", "3.1.2-RC3" ]
      cmd: scripts/test-code.sh
