name: Publish

on:
  push:
    branches: # Snapshots
      - main
      - 2.8.x
    tags: ["*"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: ihostage/.github-play/.github/workflows/publish.yml@sharable-actions
    secrets:
      username: ${{ secrets.SONATYPE_USERNAME }}
      password: ${{ secrets.SONATYPE_PASSWORD }}
      pgp_passphrase: ${{ secrets.PGP_PASSPHRASE }}
      pgp_secret: ${{ secrets.PGP_SECRET }}
